package com.jerry.work.reminder;

import com.jerry.work.service.AlertService;
import com.jerry.work.util.SpringUtil;

import java.util.Timer;
import java.util.TimerTask;

public class Reminder {
    public static void remind() {
        // TODO todo.generated by zoer
        Timer timer = new Timer();
        timer.schedule(new RemindTask(), 1000, 5000);
    }
}

class RemindTask extends TimerTask {

    @Override
    public void run() {
        AlertService bean = SpringUtil.getBean(AlertService.class);
        bean.alert();
    }

}