server:
  port: 8080
  context-path: /robot
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://t.china-healthcare.cn:3306/subscribe?useUnicode=true&characterEncoding=utf-8
    username: xbw
    password: shouke123
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
logging:
  file: log.log
saveAlertMsgUrl: "http://127.0.0.1:8082/alert/alertMsg"
aiUrl: "http://47.93.160.47:8868/nlu"
sendtmpd: "http://d.china-healthcare.cn/Wx/sendtmpmsg"
sendtmpp: "http://p.china-healthcare.cn/Wxp/sendtmpmsg"

mybatis:
  mapper-locations: /mybatis/*
  type-aliases-package: com.jerry.work.bean
  configuration:
    mapUnderscoreToCamelCase: true

