spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
mybatis:
  mapper-locations: /mybatis/*
  type-aliases-package: com.jerry.work.bean
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  file: /application/tomcat/webapps2/log/robot/robotlog.log
saveAlertMsgUrl: "http://t3.china-healthcare.cn:2503/alert/alertMsg"
aiUrl: "http://47.93.160.47:8868/nlu"
sendtmpd: "http://d.china-healthcare.cn/Wx/sendtmpmsg"
sendtmpp: "http://p.china-healthcare.cn/Wxp/sendtmpmsg"