package com.jerry.work.jennytype;

import com.jerry.work.service.MrBaiSportJenny;
import com.jerry.work.util.SpringUtil;
import org.springframework.format.datetime.DateFormatter;

import java.util.Date;
import java.util.Locale;
import java.util.Timer;
import java.util.TimerTask;

/**
 * Created by 向博文 on 2017/9/1.
 */
public class M5 {
        public static void run() {
            // TODO todo.generated by zoer
            Timer timer = new Timer();
            timer.schedule(new M5Task(), 0, 1000*60*5);//每5分钟执行一次
        }
    }

    class M5Task extends TimerTask {
        @Override
        public void run() {
            String taskStatus = "未开始";
            Date date = new Date();
            DateFormatter dateFormatter = new DateFormatter("yyyy-MM-dd HH:mm:ss");
            String start = dateFormatter.print(date, Locale.getDefault());
            MrBaiSportJenny mrBaiSportJenny = SpringUtil.getBean(MrBaiSportJenny.class);
            mrBaiSportJenny.run(taskStatus,start,"白教练");
        }

    }