package com.jerry.work.jennytype;

import com.jerry.work.service.AlertTaskJennyService;
import com.jerry.work.service.MrBaiSportJenny;
import com.jerry.work.util.SpringUtil;
import org.apache.log4j.Logger;
import org.springframework.format.datetime.DateFormatter;

import java.util.Date;
import java.util.Locale;
import java.util.Timer;
import java.util.TimerTask;

/**
 * Created by 向博文 on 2017/10/20.
 */
public class S10 {
    public static void run() {
        // TODO todo.generated by zoer
        Timer timer = new Timer();
        timer.schedule(new S10Task(), 0, 1000*60*10);//每10分钟执行一次
    }
}

class S10Task extends TimerTask {
    private Logger logger = Logger.getLogger(S10Task.class);
    @Override
    public void run() {
        String taskStatus = "未开始";
        AlertTaskJennyService alertTaskJennyService = SpringUtil.getBean(AlertTaskJennyService.class);
        try {
            alertTaskJennyService.run();
        } catch (Exception e) {
            logger.error("处理alertTaskJennyService任务发生错误");
            logger.error(e.fillInStackTrace());
        }
    }
}
