spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
            hibernate:
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    data:
      mongodb:
        uri: mongodb://skchai:skchai@101.200.44.115:3310/skchai
logging:
  file: /application/tomcat/webapps2/log/aiinterface/aiinterfacelog.log

mybatis:
  mapper-locations: /mapper/*
  type-aliases-package: com.skch.entity
  configuration:
    mapUnderscoreToCamelCase: true