server:
  port: 8081
  context-path: /aiinterface
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://t.china-healthcare.cn:3306/subscribe?useUnicode=true&characterEncoding=utf-8
    username: root
    password: S1tdq1E2tzAyOUgb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    mongodb:
      uri: mongodb://skchai:skchai@101.200.44.115:3310/skchai
  logging:
    file: ./log/log.log
mybatis:
  mapper-locations: /mapper/*
  type-aliases-package: com.skch.entity
  configuration:
    mapUnderscoreToCamelCase: true
