spring:
  devtools:
    restart:
      #以下路径下的文件被修改时重启项目
      additional-paths: src/main/java,src/main/resources/templates
      #以下路径下的文件被修改时不重启项目
      exclude: static/**
  data:
    mongodb:
      uri: mongodb://skchai:skchai@101.200.44.115:3310/skchai
server:
  port: 8081
  context-path: /mongodb
logging:
  file: d:/log/mongo/mongodb.log
  level: debug
