spring:
  freemarker:
    check-template-location: true
    template-loader-path: classpath:/templates/
    cache: false
    charset: utf-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
#  resources:
#    static-locations: classpath:/static/
　data:
　　mongodb:
　　　uri: mongodb://localhost:27017/test
