spring:
  devtools:
    restart:
      #以下路径下的文件被修改时重启项目
      additional-paths: src/main/java,src/main/resources/templates
      #以下路径下的文件被修改时不重启项目
      exclude: static/**
　data:
　　mongodb:
　　　uri: mongodb://localhost:27017/test
server:
  port: 8082